### ISSUE TITLE
Got banned

### ISSUE THREAD

**Issue by Washiii** [x00bence/Mecha#10]
Just got banned by using your tool
https://imgur.com/a/FuTVgYL

I was using it with a plugin to auto accept queue. The code for it was:
```js
const AutoAccept = Data => {
    if (Data[2].uri == "/lol-lobby-team-builder/v1/matchmaking") {
        if (Data[2].data.searchState == "Found")
            fetch("/lol-matchmaking/v1/ready-check/accept", { method: "POST" })
    }
}
```

**Comment by Celuni** [comment]
Wouldn't that spam the request even if you accepted already?
