### ISSUE TITLE
Windows DPI Settings not getting applied correctly

### ISSUE THREAD

**Issue by LoggeL** [x00bence/Mecha#2]
**Describe the bug**
Changing the DPI Scaling of a Screen doesn't get applied to the league client.

**To Reproduce**
1. Go to Display Settings
2. Change Scaling to 150% or more
3. Hook League
4. Start League

**Expected behavior**
League should be displayed correctly (as it is unhooked)

**Screenshots**
Hooked: https://cdn.discordapp.com/attachments/542307049745285120/831545180649816074/NVIDIA_Share_21-04-13_17-03-37.webp
Unhooked: https://cdn.discordapp.com/attachments/542307049745285120/831544480246136862/NVIDIA_Share_21-04-13_17-00-51.webp

**Desktop (please complete the following information):**
 - Windows 10
 - League of Legends Patch Version: 11.7
 - Antivirus (if any): Windows Defender
 
**Additional context**
- No plugins enabled

**Comment by x00bence** [comment]
Hey!

Thank you for the report, I have successfully reproduced the bug.

I am not entirely sure what is causing it. I have a feeling that the issue lies either within CEF or the client, as Mecha itself doesn't do anything that could trigger this behavior. 

I will look more into it.

**Comment by x00bence** [comment]
After reviewing the entirety of the Mecha codebase and finding nothing indicative that could be causing this issue, I will mark this issue as "out of scope" and close it for the time being. I will take a look at it again in future versions, and see what Mecha can do to potentially fix this unwanted behaviour.

A quick search yielded [this result](https://bitbucket.org/chromiumembedded/cef/issues/1445/windows-layout-is-wrong-on-initial-window), which may be closely related to this issue.
