### ISSUE TITLE
How do you replace a .js at the loading screen?

### ISSUE THREAD

**Issue by dragitz** [x00bence/Mecha#3]
Hi there, fantastic program. I really wish to implement a few gaphical changes, but to do that I would need to replace a file named ``rcp-fe-lol-champ-select.js``

I've played a bit with the plugins folder but sadly, no success.

Could you help me figure out how the plugins folder work? Thanks.

**Comment by x00bence** [comment]
Hey!

Currently speaking, there is no functionality in Mecha to replace files just like that, however I will be implementing it in the very near future, so please keep an eye out. :)

**The plugins folder right now is responsible for precisely one thing at the moment:** Loading your own code into the client. Any .js files that you place in the plugins folder will be executed in the scope of the client, before the internal Riot plugins are ran. 

**In other words:** After your plugin is loaded, you can pretty much change anything within the client, granted you know what to look for and how to reverse engineer. 

If it's very simple graphical changes (such as editing CSS), chances are you can just inject a JavaScript plugin that fetches your CSS file and applies it (places it in the DOM). You may also set up a JavaScript project with Webpack (css-loader), reference your CSS (via require), and compile it. You could inject that then.

If you are looking for something more advanced, you will have to find a way to hook the JavaScript responsible for `rcp-fe-lol-champ-select.js`.

I have been getting a lot of questions regarding plugin development, so in the near future I will also release a "boilerplate" plugin/API to help people out.
